//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDD.BrickEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TempRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TempRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDD.BrickEditor.Resources.TempRes", typeof(TempRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration.
        /// </summary>
        internal static string Label_Decoration {
            get {
                return ResourceManager.GetString("Label_Decoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration surface.
        /// </summary>
        internal static string Label_DecorationSurface {
            get {
                return ResourceManager.GetString("Label_DecorationSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration surface {0}.
        /// </summary>
        internal static string Label_DecorationSurfaceNumber {
            get {
                return ResourceManager.GetString("Label_DecorationSurfaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal model.
        /// </summary>
        internal static string Label_DefaultMeshes {
            get {
                return ResourceManager.GetString("Label_DefaultMeshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female stud.
        /// </summary>
        internal static string Label_FemaleStud {
            get {
                return ResourceManager.GetString("Label_FemaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female studs.
        /// </summary>
        internal static string Label_FemaleStudComponents {
            get {
                return ResourceManager.GetString("Label_FemaleStudComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs (female).
        /// </summary>
        internal static string Label_FemaleStuds {
            get {
                return ResourceManager.GetString("Label_FemaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed conn..
        /// </summary>
        internal static string Label_FixedConnectors {
            get {
                return ResourceManager.GetString("Label_FixedConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        internal static string Label_GearConnectors {
            get {
                return ResourceManager.GetString("Label_GearConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        internal static string Label_Geometry {
            get {
                return ResourceManager.GetString("Label_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinges.
        /// </summary>
        internal static string Label_HingeConnectors {
            get {
                return ResourceManager.GetString("Label_HingeConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main surface.
        /// </summary>
        internal static string Label_MainSurface {
            get {
                return ResourceManager.GetString("Label_MainSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male studs.
        /// </summary>
        internal static string Label_MaleStudComponents {
            get {
                return ResourceManager.GetString("Label_MaleStudComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs (male).
        /// </summary>
        internal static string Label_MaleStuds {
            get {
                return ResourceManager.GetString("Label_MaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh.
        /// </summary>
        internal static string Label_Mesh {
            get {
                return ResourceManager.GetString("Label_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string Label_Models {
            get {
                return ResourceManager.GetString("Label_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New part.
        /// </summary>
        internal static string Label_NewPartProject {
            get {
                return ResourceManager.GetString("Label_NewPartProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active project.
        /// </summary>
        internal static string Label_NoActiveProject {
            get {
                return ResourceManager.GetString("Label_NoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string Label_Part {
            get {
                return ResourceManager.GetString("Label_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part models.
        /// </summary>
        internal static string Label_PartComponents {
            get {
                return ResourceManager.GetString("Label_PartComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part %partid%.
        /// </summary>
        internal static string Label_PartProjectName {
            get {
                return ResourceManager.GetString("Label_PartProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Label_Project {
            get {
                return ResourceManager.GetString("Label_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rails.
        /// </summary>
        internal static string Label_RailConnectors {
            get {
                return ResourceManager.GetString("Label_RailConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        internal static string Label_SliderConnectors {
            get {
                return ResourceManager.GetString("Label_SliderConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stud.
        /// </summary>
        internal static string Label_Stud {
            get {
                return ResourceManager.GetString("Label_Stud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs.
        /// </summary>
        internal static string Label_Studs {
            get {
                return ResourceManager.GetString("Label_Studs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        internal static string Label_Surface {
            get {
                return ResourceManager.GetString("Label_Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfaces.
        /// </summary>
        internal static string Label_Surfaces {
            get {
                return ResourceManager.GetString("Label_Surfaces", resourceCulture);
            }
        }
    }
}
